# Generated by Django 5.1.7 on 2025-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Font Awesome class for icon', max_length=100)),
                ('proficiency', models.IntegerField(help_text='Skill level from 1 to 100')),
            ],
        ),
    ]
