# Generated by Django 5.1.7 on 2025-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to='models/designs/'),
        ),
    ]
